/**
 * Branding is isolated here so the product name can change with one edit.
 * No other module should hard-code the string "Period Mirror".
 */
export const brand = {
  name: "Period Mirror",
  shortName: "Mirror",
  tagline: "Understand your cycle by comparing your body with your own patterns.",
  mirrorSectionName: "My Mirror",
  reportName: "My Health Report",
  /** Shown on generated reports + about screen. */
  reportAttribution:
    "Generated by Period Mirror using information recorded by the user.",
  medicalDisclaimerShort:
    "Period Mirror is an informational personal health-tracking tool. It does not diagnose, treat, or give medical advice.",
  medicalDisclaimerLong:
    "Period Mirror summarizes information you record and highlights changes compared with your own history. It is not a medical device and does not diagnose, treat, or provide medical advice. Patterns it surfaces are not conclusions about your health. If a change continues, becomes severe, or concerns you, consider discussing it with a healthcare professional.",
  reportDisclaimer:
    "This report summarizes user-recorded information and is not a medical diagnosis.",
} as const;

export type Brand = typeof brand;
